#!/usr/bin/env node
// Writes extensions/specd-loop/src/version.ts so EXTENSION_VERSION matches package.json.
// Runs from package.json `prepublishOnly` so a publish always ships the right version.

/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access, no-undef */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));
const target = join(root, 'extensions/specd-loop/src/version.ts');

const content = `// This file is generated by scripts/sync-version.mjs at publish time.
// Edit package.json's "version" field instead.
export const EXTENSION_VERSION = ${JSON.stringify(pkg.version)};
`;

writeFileSync(target, content);
console.log(`synced version.ts → ${pkg.version}`);
